fix: approving tokens transfer when creating request
status-im/nim-codex pull request #385
Opened 2023-03-29 12:55 UTC by AuHau

Closes #365

2023-03-29 14:00 UTC, markspanbroek submitted a review, later dismissed
Very nice, thanks @AuHau!

2023-03-30 00:28 UTC, emizzle requested changes
Awesome Adam! Would you mind also updating the `contracts/README.md` as it specifically mentions that the codex lib doesn't include ERC20 approve functionality.

2023-03-30 04:51 UTC, AuHau commented
@emizzle Nice catch! But can you please give this PR Approve and I will fix it before merging?

2023-03-30 05:36 UTC, emizzle submitted a review, later dismissed

2023-03-30 09:34 UTC, merged